spring:
  profiles:
    group:
      development:
        - common
        - port_8080
      production-1:
        - common
        - production_database
        - port_9001
      production-2:
        - common
        - production_database
        - port_9002

---

spring:
  config:
    activate:
      on-profile: common
---

spring:
  config:
    activate:
      on-profile: production_database
  datasource:
#    url: [운영 DB]
    url: mysql-1.cow3sb5onvbq.ap-northeast-2.rds.amazonaws.com

---

spring:
  config:
    activate:
      on-profile: port_8080

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: port_9001

server:
  port: 9001

---

spring:
  config:
    activate:
      on-profile: port_9002

server:
  port: 9002